print('=============Print Function=============')
print("Programming","Essential","in", sep="***", end="...")
print("Python")
print("    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****\n"*2)
print("=============Literal================")
print("2"*2)
print(2*2)
print(type("2"))
print(type(2))
