print('==========Basic===========')
print("Hello, Phyton")
print("Saya sudah makan tadi maghrib\n dan nanti tengah malam makan lagi")
print('Saya sudah makan tadi maghrib\t dan nanti tengah malam makan lagi')
print("nama saya \"Rama\"")
print("Satu", "Dua", "Tiga")
print("Nama saya","Rama",end=" ")
print("Faisal")
print("Satu","Dua","Tiga", sep=", ")